[theme]
primaryColor = "#4e73df"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"

[server]
maxUploadSize = 5
enableCORS = true

[browser]
gatherUsageStats = false 